doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '17'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            product_id: App\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductIdType
            product_type: App\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductTypeType
            product_title: App\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductTitleType
            ean: App\Catalog\Product\Infrastructure\Persistence\Doctrine\EanType
            product_description: App\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductDescriptionType
            product_year: App\Catalog\Product\Infrastructure\Persistence\Doctrine\ProductYearType
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: false
        mappings:
            CatalogProduct:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Product/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Catalog\Product\Domain'
                alias: CatalogProduct

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
